---
- name: add elasticsearch repository
  template: src=elasticsearch.repo.j2 dest=/etc/yum.repos.d/elasticsearch-{{ elasticsearch_major_version }}.repo

- name: Install elasticsearch
  yum: name=elasticsearch state=present enablerepo=elasticsearch-{{ elasticsearch_major_version }}.x

- name: Copy elasticsearch.yml
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml mode=0644
  notify: restart elasticsearch

- name: Set automatic start of elasticsearch
  systemd: name=elasticsearch state=started enabled=yes
