# file: Vagrantfile
Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.4"

  config.vm.define "crowiplus" do |crowiplus|
    crowiplus.vm.hostname = "crowiplus"
    crowiplus.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "mongodb" do |mongodb|
    mongodb.vm.hostname = "mongodb"
    mongodb.vm.network "private_network", ip: "192.168.56.11"
  end

  config.vm.define "redis" do |redis|
    redis.vm.hostname = "redis"
    redis.vm.network "private_network", ip: "192.168.56.12"
  end

  config.vm.define "elasticsearch" do |elasticsearch|
    elasticsearch.vm.hostname = "elasticsearch"
    elasticsearch.vm.network "private_network", ip: "192.168.56.13"
  end

  config.vm.define 'controller' do |controller|

  controller.vm.network "private_network", ip: "192.168.56.5"
  controller.vm.provision "file", source: ".vagrant/machines/crowiplus/virtualbox/private_key", destination: "/home/vagrant/.ssh/crowiplus.private_key"
  controller.vm.provision "file", source: ".vagrant/machines/mongodb/virtualbox/private_key", destination: "/home/vagrant/.ssh/mongodb.private_key"
  controller.vm.provision "file", source: ".vagrant/machines/redis/virtualbox/private_key", destination: "/home/vagrant/.ssh/redis.private_key"
  controller.vm.provision "file", source: ".vagrant/machines/elasticsearch/virtualbox/private_key", destination: "/home/vagrant/.ssh/elasticsearch.private_key"

  controller.vm.provision "shell", inline: <<-SHELL
    chmod 600 -R /home/vagrant/.ssh/*.private_key
    chown vagrant:vagrant -R /home/vagrant/.ssh/*.private_key
  SHELL

  controller.vm.provision :ansible_local do |ansible|
      ansible.playbook       = "./playbook/site.yml"
      ansible.verbose        = true
      ansible.install        = true
      ansible.limit          = "all" # or only "nodes" group, etc.
      ansible.inventory_path = "./playbook/hosts/local"
    end
  end

end
