---
- name: add nodesource repository
  yum_repository:
    name: nodesource
    description: Node.js Packages for Enterprise Linux 7 - $basearch
    baseurl: https://rpm.nodesource.com/pub_6.x/el/7/$basearch
    failovermethod: priority
    enabled: no
    gpgcheck: no
    gpgkey: file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

- name: add nodesource-source repository
  yum_repository:
    name: nodesource-source
    description: Node.js for Enterprise Linux 7 - $basearch - Source
    baseurl: https://rpm.nodesource.com/pub_6.x/el/7/SRPMS
    failovermethod: priority
    enabled: no
    gpgcheck: no
    gpgkey: file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

- name: install nodejs
  yum: name=nodejs state=present enablerepo=nodesource

- name: install yarn
  npm:
    name: yarn
    global: yes
    state: present

- name: install npm-install-missing
  npm:
    name: npm-install-missing
    global: yes
    state: present
