---
- name: Install chrony
  yum:
    name: chrony
    state: present

- name: Chrony update the chrony.conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart chrony

- name: Set automatic start of chrony
  systemd: name=chronyd state=started enabled=yes
