# file: Vagrantfile
VAGRANTFILE_API_VERSION = "2"
VAGRANT_PROVIDER = "virtualbox"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-7.4"

  config.vm.define "simple" do |simple|
    simple.vm.hostname = "simple"
    simple.vm.network "private_network", ip: "192.168.56.21"
  end

  config.vm.define 'controller' do |controller|
  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "../common_roles", "/common_roles"

  controller.vm.network "private_network", ip: "192.168.56.20"

  controller.vm.provision "file", source: ".vagrant/machines/simple/#{VAGRANT_PROVIDER}/private_key", destination: "/home/vagrant/.ssh/simple.private_key"

  controller.vm.provision "shell", inline: <<-SHELL
    chmod 600 -R /home/vagrant/.ssh/*.private_key
    chown vagrant:vagrant -R /home/vagrant/.ssh/*.private_key
  SHELL

  controller.vm.provision :ansible_local do |ansible|
      ansible.playbook       = "./playbook/site.yml"
      ansible.verbose        = true
      ansible.install        = true
      ansible.limit          = "all"
      ansible.inventory_path = "./playbook/hosts/local"
    end
  end
end
