---
- name: Install redis
  yum: name=redis state=present enablerepo=epel

- name: Copy redis.conf
  template: src=redis.conf.j2 dest=/etc/redis.conf mode=0644
  notify: restart redis

- name: Set automatic start of redis
  systemd: name=redis state=started enabled=yes
