---
- name: install requirements packages
  yum: name="{{ item  }}" state=present
  with_items:
    - libselinux-python
    - libsemanage-python

- name: change seLinux state
  selinux:
    policy: targeted
    state: "{{ selinux_state }}"
  register: selinux_result

- name: Reboot. If SELinux state is changed
  shell: sleep 2 && shutdown -r now "reboot"
  become: yes
  async: 1
  poll: 0
  ignore_errors: true
  when: selinux_result.changed

- name: Wait reboot. If SELinux state is changed
  local_action: wait_for host={{  ansible_host  }} port=22 delay=30 state=started
  become: false
  when: selinux_result.changed
