# file: Vagrantfile
Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.4"

  config.vm.define "crowiplus" do |crowiplus|
    crowiplus.vm.hostname = "crowiplus"
    crowiplus.ssh.insert_key = false
    crowiplus.vm.network "private_network", ip: "192.168.33.10"
    crowiplus.vm.provision "ansible" do |ansible|
      #ansible.verbose = "vvvv"
      ansible.limit = "all"
      ansible.inventory_path = "./playbook/hosts/local"
      ansible.playbook = "./playbook/crowiplus.yml"
    end
  end

  config.vm.define "mongodb" do |mongodb|
    mongodb.vm.hostname = "mongodb"
    mongodb.ssh.insert_key = false
    mongodb.vm.network "private_network", ip: "192.168.33.11"
    mongodb.vm.provision "ansible" do |ansible|
      #ansible.verbose = "vvvv"
      ansible.limit = "all"
      ansible.inventory_path = "./playbook/hosts/local"
      ansible.playbook = "./playbook/mongodb.yml"
    end
  end

  config.vm.define "redis" do |redis|
    redis.vm.hostname = "redis"
    redis.ssh.insert_key = false
    redis.vm.network "private_network", ip: "192.168.33.12"
    redis.vm.provision "ansible" do |ansible|
      #ansible.verbose = "vvvv"
      ansible.limit = "all"
      ansible.inventory_path = "./playbook/hosts/local"
      ansible.playbook = "./playbook/redis.yml"
    end
  end

  config.vm.define "elasticsearch" do |elasticsearch|
    elasticsearch.vm.hostname = "elasticsearch"
    elasticsearch.ssh.insert_key = false
    elasticsearch.vm.network "private_network", ip: "192.168.33.13"
    elasticsearch.vm.provision "ansible" do |ansible|
      #ansible.verbose = "vvvv"
      ansible.limit = "all"
      ansible.inventory_path = "./playbook/hosts/local"
      ansible.playbook = "./playbook/elasticsearch.yml"
    end
  end

end
