---
postfix_myhostname: 'mail.example.local'
postfix_mydomain: 'example.local'

postfix_inet_interfaces: 'localhost'
postfix_inet_protocols: 'all'

postfix_mydestination: '$myhostname, localhost.$mydomain, localhost, $mydomain'
postfix_mynetworks: '127.0.0.0/8'

postfix_home_mailbox: 'Maildir/'
postfix_smtpd_banner: '$myhostname ESMTP'

postfix_message_size_limit: '10485760'
postfix_mailbox_size_limit: '1073741824'

postfix_bounce_queue_lifetime: '1d'
postfix_maximal_queue_lifetime: '1d'

postfix_use_submission_port: true

postfix_db_username: 'postfix'
postfix_db_password: 'postfix'
postfix_db_name: 'postfix'

dovecot_mail_location: 'maildir:~/'
dovecot_valid_uid: '10000'
dovecot_valid_gid: '10000'
dovecot_valid_chroot_dirs: '/home/virtual_mailbox'

dovecot_ssl: 'no'

dovecot_dovecot_disable_plaintext_auth: 'no'
dovecot_auth_default_realm: 'example.local'
dovecot_auth_username_format: '%Lu'
dovecot_auth_mechanisms: 'plain login digest-md5 cram-md5'

dovecot_include_conf:
  - '!include auth-sql.conf.ext'
