---
- name: simple
  hosts: simple
  become: true

  vars_files:
    - ../../common_roles/vars/common.yml
  roles:
    - ../../common_roles/roles/hostname
    - ../../common_roles/roles/selinux
    - ../../common_roles/roles/firewalld
    - ../../common_roles/roles/epel
    - ../../common_roles/roles/chrony
    - ../../common_roles/roles/basic_web_server
    - ../../common_roles/roles/vsftpd
#    - ../../common_roles/roles/nodejs
#    - ../../common_roles/roles/crowiplus
