---
- name: add mongodb repository
  yum_repository:
    name: mongodb
    description: MongoDB Repository
    baseurl: http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
    enabled: no
    gpgcheck: no

- name: Install mongodb
  yum: name=mongodb-org state=present enablerepo=mongodb

- name: Install python pip,virtualenv,devel
  yum: name={{ item }} state=present enablerepo=epel
  with_items:
    - python-pip
    - python-virtualenv
    - python-devel

- name: Copy mongod.conf
  template: src=mongod.conf.j2 dest=/etc/mongod.conf mode=0644
  notify: restart mongod

- name: Set automatic start of mongod
  systemd: name=mongod state=started enabled=yes

- name: pymongo
  pip: name=pymongo

- name: mongod add user adimin
  mongodb_user:
    database: admin
    name: "{{ mongodb_admin_username }}"
    password: "{{ mongodb_admin_userpassword }}"
    update_password: on_create
    state: present
