---
- name: Install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: Change permissions of CrowiPlus dir
  file: path=/opt/crowiplus mode=755 state=directory owner=root

- name: Download CrowiPlus (git clone)
  git: repo=https://github.com/weseek/crowi-plus dest=/opt/crowiplus update=no

- name: Confirm whether CrowiPlus is installed
  stat: path=/opt/crowiplus/node_modules
  register: node_modules

- name: Install CrowiPlus
  shell: /usr/bin/yarn
  args:
    chdir: /opt/crowiplus
  when: not node_modules.stat.exists

- name: Copy systemd service file of CrowiPlus
  copy: src=crowiplus.service dest=/etc/systemd/system/crowiplus.service mode=0644

- name: Copy systemd sysconfig file of CrowiPlus
  template: src=crowiplus.sysconfig.j2 dest=/etc/sysconfig/crowiplus owner=root mode=0600

- name: Set automatic start of crowiplus
  systemd: name=crowiplus state=started enabled=yes daemon_reload=yes
